jdr_core_home:
    path: /accueil
    defaults:
        _controller: JDRCoreBundle:Core:index

jdr_core_session_creation:
    path: /creation-partie
    defaults:
        _controller: JDRCoreBundle:Session:createSession

jdr_core_session_destroy:
    path: /supprimer-partie/{id}
    defaults:
        _controller: JDRCoreBundle:Session:removeSession

jdr_core_game_edition:
    path: /partie/mj/{id}
    defaults:
        _controller: JDRCoreBundle:Session:editSession


jdr_core_ajax:
    resource: "@JDRCoreBundle/Resources/config/routingAjax.yml"
    prefix:   /ajax


