jdr_core_ajax_username:
    path: /username
    defaults:
        _controller: JDRCoreBundle:Core:username
        methods: [post]

jdr_core_ajax_remove_stat_session:
    path: /remove-stat
    defaults:
        _controller: JDRCoreBundle:Session:removeStat
        metthods: [post]

jdr_core_ajax_add_stat_session:
    path: /add-stat
    defaults:
        _controller: JDRCoreBundle:Session:addStat
        methods: [post]

jdr_core_ajax_send_invitation:
    path: /add-player
    defaults:
        _controller: JDRCoreBundle:Invitation:addPlayer
        methods: [post]

jdr_core_ajax_find_invitation:
    path: /find-invit
    defaults:
        _controller: JDRCoreBundle:Invitation:findInvitations
        methods: [post]

jdr_core_ajax_cancel_invitation:
    path: /cancel-invit
    defaults:
        _controller: JDRCoreBundle:Invitation:cancelInvitation
        methods: [post]

jdr_core_ajax_remove_player:
    path: /remove-player
    defaults:
        _controller: JDRCoreBundle:Invitation:removePlayer
        methods: [post]

jdr_core_ajax_send_again:
    path: /send-again
    defaults:
        _controller: JDRCoreBundle:Invitation:sendAgainInvitation
        methods : [post]

jdr_core_ajax_accept_invitation:
    path: /accept
    defaults:
        _controller: JDRCoreBundle:Core:acceptInvitation
        methods : [post]