jdr_core_ajax_username:
    path: /username
    defaults:
        _controller: JDRCoreBundle:Core:username
        methods: [post]


jdr_core_ajax_send_invitation:
    path: /add-player
    defaults:
        _controller: JDRCoreBundle:Invitation:addPlayer
        methods: [post]

jdr_core_ajax_find_invitation:
    path: /find-invit
    defaults:
        _controller: JDRCoreBundle:Invitation:findInvitations
        methods: [post]


jdr_core_ajax_remove_player:
    path: /remove-player
    defaults:
        _controller: JDRCoreBundle:Invitation:removePlayer
        methods: [post]

jdr_core_ajax_send_again:
    path: /send-again
    defaults:
        _controller: JDRCoreBundle:Invitation:sendAgainInvitation
        methods : [post]

jdr_core_ajax_accept_invitation:
    path: /accept
    defaults:
        _controller: JDRCoreBundle:Invitation:acceptInvitation
        methods : [post]