<?php

namespace JDR\CoreBundle\Repository;
use JDR\CoreBundle\JDRCoreBundle;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Renvoie le statut et le nom des joueurs invité à la session passée en paramètre
     */
    public function findNameAndStatut($idSession){

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('i.statut, p.username')
            ->from('JDRCoreBundle:Invitation', 'i')
            ->innerJoin('i.player', 'p')
            ->innerJoin('i.session', 's')
            ->where('s.id = :session_id')
            ->setParameter('session_id', $idSession)
            ->getQuery()
            ->getResult();
    }

    /**
     * Retourne l'invitation qui possède les paramètres saisis
     */
    public function findByNameAndIdSession($playerName, $idSession){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('i')
            ->from('JDRCoreBundle:Invitation', 'i')
            ->innerJoin('i.player', 'p')
            ->innerJoin('i.session', 's')
            ->where('p.username = :username')
            ->andWhere('s.id = :session_id')
            ->setParameter('username', $playerName)
            ->setParameter('session_id', $idSession)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * Renvoie toutes les sessions où l'utilisateur a reçu des invitations
     * Revnoie le nom de la session, l'id de l'inviation et l'id de la session
     */
    public function findSessionsInvit($playerId){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select("s.name, i.id")
            ->from("JDRCoreBundle:Invitation", 'i')
            ->innerJoin('i.player', 'p')
            ->innerJoin('i.session', 's')
            ->where('p.id = :player_id')
            ->andWhere('i.statut = :statut')
            ->setParameter('player_id', $playerId)
            ->setParameter('statut', 'wait')
            ->getQuery()
            ->getResult();
    }
}
